name: Build and Push Python App to Amazon ECR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "app.py"
      - "requirements.txt"
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/build-and-push-ecr.yml"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      ECR_REPOSITORY: aws-terraform-infrastructure-python-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::428516841589:role/github-actions-oidc-aws-terraform-infrastructure-main
          role-session-name: github-actions-ecr-rce-44

      - name: Show caller identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $REGISTRY/$ECR_REPOSITORY:latest \
            .

      - name: Push Docker image tags to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$ECR_REPOSITORY:latest
