name: Deploy Terraform to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/deploy-terraform.yml"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::428516841589:role/github-actions-oidc-aws-terraform-infrastructure-main
          role-session-name: github-actions-terraform-rce-43

      - name: Show caller identity
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6
          terraform_wrapper: false

      - name: Terraform fmt
        run: terraform fmt -check -recursive -no-color

      - name: Terraform init
        run: terraform init -input=false -no-color

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform apply
        run: terraform apply -input=false -no-color tfplan
