name: Test AWS OIDC Role

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::428516841589:role/github-actions-oidc-aws-terraform-infrastructure-main
          role-session-name: github-oidc-test

      - name: Verify who AWS thinks I am
        run: aws sts get-caller-identity

      - name: Verify EC2 read permission
        run: aws ec2 describe-regions --region eu-west-1 --output table
